PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
 
CONSTRUCT {
    ?URIresource a ?URItype;
        rdfs:label ?label;
}
FROM <file:test2.csv>
WHERE {
    BIND (URI(?type) AS ?URItype)
    BIND (URI(?resource) AS ?URIresource)
}
